### ISSUE TITLE
ElasticSearch 6.3 requires keystore file to exist

### ISSUE THREAD

**Issue by colin-stubbs** [saltstack-formulas/elasticsearch-formula#54]
ES 6.3 won't start without a keystore file existing. On many systems the user/group/context that ES runs in does not, and should not, have permission to create files in /etc/elasticsearch. Formula should create a default keystore in default location if one does not exist.

Jul 20 14:05:11 box systemd[1]: Starting Elasticsearch...
Jul 20 14:05:12 box elasticsearch[85725]: Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.elasticsearch.cli.UserException: unable to create temporary keystore at [/etc/elasticsearch/elasticsearch.keystore.tmp], please check filesystem permissions
Jul 20 14:05:12 box elasticsearch[85725]: Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/elasticsearch.keystore.tmp
Jul 20 14:05:12 box elasticsearch[85725]: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
Jul 20 14:05:12 box elasticsearch[85725]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
Jul 20 14:05:12 box elasticsearch[85725]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
Jul 20 14:05:12 box elasticsearch[85725]: at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
Jul 20 14:05:12 box systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE

**Comment by phornkrit** [comment]
Push
